name: ci

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # - name: golangci-lint
    #   uses: golangci/golangci-lint-action@v3

    - name: CI
      run: make ci
